# Generated by Django 3.2.25 on 2025-02-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
