# Generated by Django 3.2.25 on 2025-02-13 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_auto_20250213_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_items',
        ),
        migrations.AddField(
            model_name='order',
            name='cart_items',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='cart.cartitem'),
        ),
    ]
