# Generated by Django 3.2.25 on 2025-02-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20250205_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='Image', max_length=50),
        ),
    ]
